### PR TITLE
Webmonkeys: Code in the Dark Ad

### PR DESCRIPTION
**Pull request by pranaygp**
Added an ad for Code in the Dark next Tuesday

### CODE REVIEW

**Comment by pranaygp** [comment]
I don't actually know why the build is failing: https://travis-ci.org/acm-uiuc/display/builds/295998837?utm_source=github_status&utm_medium=notification

I don't think it's my fault. Can someone check and lmk? I'm guessing it was already failing

**Comment by kevinwang** [comment]
It doesn't look like CI should be enabled for this repo yet. See https://github.com/acm-uiuc/display/issues/26

**Comment by pranaygp** [comment]
The issue clearly days Travis CI is enabled? I'm pretty confused :/

In that case, is someone able to override the CI and just merge this in anyway?

**Comment by bcongdon** [comment]
Yeah, this is fine. I'll disable CI for now and merge this.

**Comment by pranaygp** [comment]
Thanks :) does merging it in automatically update display, or does some need to manually ssh in, git pull and restart the server?

**Comment by bcongdon** [comment]
Someone needs to do it manually to pull/restart

**Pull request merged**
